extends Node

## Global Game Events (Autoload)
## Create a script called GameEvents.gd and add to Project Settings -> Autoload

signal flashlight_toggled(is_on: bool)
signal player_detected()
signal signal radio_static_intensity(level: float)
signal presence_intensity_changed(level: float)
signal interaction_prompt_toggled(visible: bool, text: String)
signal item_collected(item_id: String)
signal item_used(item_id: String)
signal resource_critical(resource_id: String)
signal stealth_state_changed(is_crouching: bool)
signal dialogue_started(dialogue_id: String)
signal dialogue_line_displayed(text: String, options: Array)
signal dialogue_finished()
signal quest_started(quest_id: String)
signal quest_updated(quest_id: String, progress: float)
signal quest_completed(quest_id: String)
signal anxiety_level_changed(value: float)
signal paranoia_level_changed(value: float)
signal moral_choice_made(choice_id: String, alignment_shift: float)
signal time_distortion_active(scale: float)
signal flashback_triggered(scene_id: String)
signal invisible_threat_proximity(dist: float)
signal perspective_shift_requested(type: String)
signal environment_event_triggered(type: String)
signal perception_distortion_updated(saturation: float, tint: Color)
signal clue_found(clue_text: String)
signal checkpoint_reached(pos: Vector2)
signal achievement_unlocked(id: String, title: String)
signal game_saved()
signal game_loaded()
